splits:
  - prefix: "src/webauthn"
    target: "https://${GH_TOKEN}@github.com/web-auth/webauthn-lib.git"
  - prefix: "src/stimulus"
    target: "https://${GH_TOKEN}@github.com/web-auth/ux.git"
  - prefix: "src/symfony"
    target: "https://${GH_TOKEN}@github.com/web-auth/webauthn-symfony-bundle.git"

origins:
  - ^\d+\.\d+\.x$
  - ^\d+\.\d+\.\d+$
