splits:
  - prefix: "src/webauthn"
    target: "https://${GH_TOKEN}@github.com/web-auth/webauthn-lib.git"
  - prefix: "src/stimulus"
    target: "https://${GH_TOKEN}@github.com/web-auth/ux.git"
  - prefix: "src/symfony"
    target: "https://${GH_TOKEN}@github.com/web-auth/webauthn-symfony-bundle.git"
  - prefix: "src/metadata-service"
    target: "https://${GH_TOKEN}@github.com/web-auth/webauthn-metadata-service.git"

origins:
  - ^(1|2|3|4)\.\d+\.x$
  - ^(1|2|3|4)\.\d+\.\d+$
